name: Build

defaults:
  run:
    shell: bash -eo pipefail {0}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [bookworm, trixie]
        flutter: [3.19.6, 3.22.0]
      fail-fast: false

    container:
      image: debian:${{ matrix.os }}

    steps:
      - name: Install basic dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y \
            bash curl file git coreutils zip unzip which xz-utils jq
          
          git config --global --add safe.directory '*'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ matrix.flutter }}

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev \
            libmpv-dev

      - name: Fetch code
        run: |
          git clone https://github.com/ubuntu-flutter-community/musicpod
          cd musicpod
          git checkout -f 6cd53fc4378cb3eda814d512db9baa77116bc94e

      - name: Build
        run: |
          cd musicpod
          flutter pub get
          flutter build linux --debug -v
